# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)
Category.delete_all
[{:level => 1,:url => '#',:name => '服装、内衣、配件',:desc => 'This is category 服装、内衣、配件'},{:level => 1,:url => '#',:name => '珠宝饰品、手表眼镜',:desc => 'This is category 珠宝饰品、手表眼镜'},{:level => 1,:url => '#',:name => '化妆品',:desc => 'This is category 化妆品'},{:level => 1,:url => '#',:name => '运动、户外',:desc => 'This is category 运动、户外'},{:level => 1,:url => '#',:name => '手机、数码',:desc => 'This is category 手机、数码'},{:level => 1,:url => '#',:name => '家用电器',:desc => 'This is category 家用电器'},{:level => 1,:url => '#',:name => '家具、建材',:desc => 'This is category 家具、建材'},{:level => 1,:url => '#',:name => '居家生活',:desc => 'This is category 居家生活'},{:level => 1,:url => '#',:name => '食品、保健',:desc => 'This is category 食品、保健'},{:level => 1,:url => '#',:name => '母婴用品',:desc => 'This is category 母婴用品'},{:level => 1,:url => '#',:name => '汽车、配件',:desc => 'This is category 汽车、配件'},{:level => 1,:url => '#',:name => '文化、玩乐',:desc => 'This is category 文化、玩乐'},{:level => 1,:url => '#',:name => '冬季保湿',:desc => 'This is category 冬季保湿'},{:level => 1,:url => '#',:name => '精致彩妆',:desc => 'This is category 精致彩妆'},{:level => 1,:url => '#',:name => '经典香氛',:desc => 'This is category 经典香氛'},{:level => 1,:url => '#',:name => '体面男士',:desc => 'This is category 体面男士'},{:level => 1,:url => '#',:name => '精油芳疗',:desc => 'This is category 精油芳疗'},{:level => 1,:url => '#',:name => '周身保养',:desc => 'This is category 周身保养'},{:level => 1,:url => '#',:name => '珠宝配饰',:desc => 'This is category 珠宝配饰'},{:level => 1,:url => '#',:name => '住宅家具',:desc => 'This is category 住宅家具'},{:level => 1,:url => '#',:name => '商业家具',:desc => 'This is category 商业家具'},{:level => 1,:url => '#',:name => '精品家纺',:desc => 'This is category 精品家纺'},{:level => 1,:url => '#',:name => '家饰软装',:desc => 'This is category 家饰软装'},{:level => 1,:url => '#',:name => '家装主材',:desc => 'This is category 家装主材'},{:level => 1,:url => '#',:name => '电工基建',:desc => 'This is category 电工基建'},{:level => 1,:url => '#',:name => '家居服务',:desc => 'This is category 家居服务'},{:level => 1,:url => '#',:name => '灯饰照明',:desc => 'This is category 灯饰照明'}].each do |category|
  Category.create(:level => category[:level],:name => category[:name],:desc => category[:desc],:url => category[:url])
end